# Generated by Django 4.0.8 on 2022-10-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_id', models.IntegerField()),
                ('investment_id', models.IntegerField()),
                ('fees_amount', models.IntegerField()),
                ('date_added', models.DateField()),
                ('fees_type', models.CharField(max_length=10)),
            ],
        ),
    ]
