# Generated by Django 4.0.8 on 2022-10-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('credit', models.CharField(max_length=60)),
                ('email_send', models.EmailField(max_length=254)),
                ('date_added', models.DateTimeField()),
                ('invoice_status', models.CharField(max_length=10)),
            ],
        ),
    ]
