# Generated by Django 4.0.8 on 2022-10-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashcalls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Investments',
            new_name='Cashcalls',
        ),
    ]
